### PR TITLE
Add home button to error boundary

### LINKED ISSUE #3515: No way to go back on desktop if error
## What went wrong? 😲
My desktop error'd and now I can't go back D: and am stuck in an endless loop of trying to press try again. This will happen if any changes breaks something, so probably not an issue if everything is functioning as it should but when it doesn't....................

https://github.com/msupply-foundation/open-msupply/assets/61820074/460a70fb-c20a-42e7-a1d0-10335fc5ca54

## Expected behaviour 🤔
Should be able to go back if the page won't load

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version: 1.7
- Legacy mSupply Central Server Version:

- Platform: Desktop (electron)

- Database type:

### PR DESCRIPTION
**Pull request by fergie-nz**
Fixes #3515 

# 👩🏻‍💻 What does this PR do?
Adds link to navigate back to home from error

## 💌 Any notes for the reviewer?

# 🧪 Testing

I was a bit dissatisfied with working through how to test this because a lot of errors thrown will not be caught by our error handler. 

A future issue could be more comprehensive error catching with this provider.

@Roxy I wonder how you were able to trigger the error in this way? 

Regardless this will allow users to navigate back to home where their current url triggers the error for whatever reason.

### CODE REVIEW

**Review by clemens-msupply — APPROVED** [review]
Nice! Think a tooltip showing the "home" origin url would be helpful, maybe easy to add?

For testing, I added a `throw Error();` statement in my code I got this when navigating to the affected page:

image

Nit, it doesn't help when the error happens on the dashboard page, but then there is not much you can do about it :)

Nit, wonder if there is a better name for "home"? Not sure if it is 100% clear...
You could add a tool tip displaying the origin, think this would make it clearer.

**Review by roxy-dao — CHANGES_REQUESTED** [review]
This doesn't work for the electron app... still no way to go back

**Comment by clemens-msupply** [comment]
> This doesn't work for the electron app... still no way to go back

Right, is this a dev issue or a production issue. I tried to figure out what causes it in dev but couldn't quite figure it out... The problem I am seeing is that the GenericErrorFallback is not responsive, i.e. I can't click on the home or retry button. There is a workaround though, you can go into dev tools and back and then you will see another React error screen and afterwards you can click the home button.

I just tried it out in release mode, and it works fine there.

Not sure if somebody else has an idea how to fix it but could be problem that is a bit harder to fix?

Note, even though I thought I built everything correctly, in release mode, I see this:
image

**Comment by fergie-nz** [comment]
Hey @clemens-msupply , Roxy and I are struggling to get electron to throw an error.

I wonder would you be willing to show us when you get a moment? Perhaps tomorrow in office?

**Comment by mark-prins** [comment]
I can break it 🤷  will show

**Review by roxy-dao — APPROVED** [review]
Thanks Ferg <3

**Comment by mark-prins** [comment]
Just added some notes to the readme on testing the boundary

**Pull request merged**
