### PR TITLE
4117 replace FEATURE_GAPS flag with vaccine module check

### LINKED ISSUE #4117: Hide GAPS work behind Vaccine Module preference
## Is your feature request related to a problem? Please describe 👀

GAPS features don't make much sense without the Vaccine module enabled, so they should only be visible if the Vaccine module preference is on. 

While you're at it - remove the GAPS feature flag, we want these things visible for 2.1!

### Moneyworks Jobcode 🧰

CCEIDEV

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #4117

NOTE: #4103 needs to be included in this! I didn't want to stack, but whatever gets merged first...

# 👩🏻‍💻 What does this PR do?

Uses vaccine module to enable/disable GAPS features, and removes feature flag

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] In mSupply, disable `Vaccine module` preference
- [ ] In omSupply (central), in the Nav Drawer, you CANNOT see:
  - [ ] Manage section
  - [ ] Programs section
  - [ ] Catalogue > Demographics page
- [ ] In mSupply, enable `Vaccine module` preference
- [ ] In omSupply (central), in the Nav Drawer, you CAN see:
  - [ ] Manage section
  - [ ] Programs section
  - [ ] Catalogue > Demographics page (note, this might end up under `Manage` at some stage

# 📃 Documentation

- [x] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

**Comment by jmbrunskill** [comment]
I wonder if Catalogue -> Assets should be behind this preference too? Not a major but could be a tidy up?
image

@adamdewey, will all stores that need to add their population, Level, etc have the vaccine module enabled? I think the answer is yes as they'll be managing their CC assets right?

Just wondering if https://github.com/msupply-foundation/open-msupply/pull/4103 (Remote store editing properties) should be behind this feature or not. Feeling like might be ok to keep it enabled, or maybe only enabled if name properties are defined?

**Review by jmbrunskill — APPROVED** [review]
Looks good to me.

I assume this duplicate button is in develop, as I don't see how this could be introduced here?
image

**Comment by adamdewey** [comment]
> I wonder if Catalogue -> Assets should be behind this preference too? Not a major but could be a tidy up? 
I don't think it should be - as general asset management doesn't necessarily mean they will be using the CCEI module (they might just want to manage general assets in the yet-to-be-developed general assets module)
However we could potentially hide the WHO PQS Sub-catalogue to only appear when the vaccine preference is turned on.

> @adamdewey, will all stores that need to add their population, Level, etc have the vaccine module enabled? I think the answer is yes as they'll be managing their CC assets right?
At that moment that's true - but I can imagine that other functionality might want to make use of supplementary facility-related data at some point?

> Just wondering if #4103 (Remote store editing properties) should be behind this feature or not. Feeling like might be ok to keep it enabled, or maybe only enabled if name properties are defined?
Again, may be useful for other functionality that wants to use supplementary facility data at some stage?

**Comment by lache-melvin** [comment]
Ok thanks team - leaving footer edit button, probably to only be displayed when properties are defined. And leaving assets always visible 🙏

**Pull request merged**
