### PR TITLE
Update default log level to Info

### LINKED ISSUE #5070: Default log level on windows service should be `Info`
## Is your feature request related to a problem? Please describe 👀

It looks like our installations are going out with a default Log Level of `Warn` I'm not sure if this is in the installer?

## Describe the solution you'd like 🎁

We should be logging a `info` level as a default. This means we'll see things like running migrations in the logs rather then nothing when the server starts up.

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #5070

# 👩🏻‍💻 What does this PR do?

Updates the default Log Level in our installers to Info.
This will provide a lot more info to our support team when investigating any issues.

## 💌 Any notes for the reviewer?

Untested :(
Will need to run a build through Jenkins to test, then install a fresh copy...

# 🧪 Testing

- [ ] Build in Jenkins
- [ ] Install a fresh copy of OMS via installer
- [ ] Check Log level

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [X] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

**Comment by jmbrunskill** [comment]
@raviSussol I editing the file in my editor and is has reformatted stuff which look like it might not be ideal

**Comment by lache-melvin** [comment]
Could tag your commit on this branch to build the test installer now? Also just double checking this isn't any more urgent than 2.4? 🙏

**Comment by jmbrunskill** [comment]
Tagged, it would be nice to go out with 2.3.0 I think but didn't want to compromise the RC...

**Review by lache-melvin — APPROVED** [review]
Code looks all good, will wait to hear from Kahn testing it 🙏 

Also happy to throw this in 2.3 if you're game 🚀

**Comment by kahn-msupply** [comment]
> Code looks all good, will wait to hear from Kahn testing it 🙏
> 
> Also happy to throw this in 2.3 if you're game 🚀

I can confirm local.yaml files for Server, Standalone, and Server Demo have log level set by default to 'Info'. **LGTM!**

**Pull request merged**
