### PR TITLE
Add login to graphql playground

### LINKED ISSUE #3378: Add a login button to graphql playground
## Is your feature request related to a problem? Please describe 👀

Bring in [this PR](https://github.com/msupply-foundation/notify/pull/155)
I thought that I'd made an issue already, but cannot find it.

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #3378

# 👩🏻‍💻 What does this PR do? 
 
Simply brings the changes through from the original PR.
You can now login if you use the /graphql endpoint. Doesn't help me with [graphiql](https://cloud.hasura.io/public/graphiql] which is what I normally use.. might be time to switch over though. the login is super useful.

https://github.com/msupply-foundation/open-msupply/assets/9192912/60820c3a-6785-4db2-962c-592c8c303084

# 🧪 How has/should this change been tested? 

## 📃 Documentation

_No user facing changes_

or

- [ ] Functional change 1
- [ ] Functional change 2

### CODE REVIEW

**Review by clemens-msupply — COMMENTED** [review]
Great! I noticed that the "Show GraphiQL Explorer" link is not working for me...

**Review by roxy-dao — APPROVED** [review]
Awesome!

**Comment by jmbrunskill** [comment]
> Great! I noticed that the "Show GraphiQL Explorer" link is not working for me...

Yeah it's broken in notify & universal codes too. Would be great to fix it before we merge!
I think it's the library we're pulling from the internet, maybe need to save more dependencies locally so we don't have version miss matches...

**Comment by mark-prins** [comment]
Fixed the graphiql explorer 😄

**Pull request merged**
