### PR TITLE
Use uuid v7 instead of v4

### LINKED ISSUE #4038: Use UUIDv7 instead of v4
## The suggestion

Since uuid7 produces time sortable ids, using uuid7 as primary key should result in better DB performance. For example, it's much more likely that all stocktake lines of a newly created stocktake are in consecutive blocks on disk while with uuid v4 rows are scattered all over the disk...

Please see https://uuid7.com/ for details.

@jmbrunskill 

We already abstract over the used uuid method. So very easy to change.

### PR DESCRIPTION
**Pull request by clemens-msupply**
Using uuid v7 improves write and improves read performance for sequential reads.

Fixes #4038

### CODE REVIEW

**Review by jmbrunskill — COMMENTED** [review]
Aren't most of our UUIDs generated from the frontend?
Does this exist for typescript? I assume it does?

**Comment by clemens-msupply** [comment]
> Aren't most of our UUIDs generated from the frontend? Does this exist for typescript? I assume it does?

ah yes you are right, would have to do it on the frontend

**Comment by clemens-msupply** [comment]
Haha merged 3 days ago: https://github.com/uuidjs/uuid/pull/681 but last release was 9 month ago...

**Comment by clemens-msupply** [comment]
I had a look at the uuidv7 nodejs package https://www.npmjs.com/package/uuidv7. Also had a brief browse through the repo and it looks good to me...

**Review by jmbrunskill — APPROVED** [review]
Looks good to me...

**Pull request merged**
