### PR TITLE
5090 bug fix eternal loading 

### LINKED ISSUE #5090: Quitting report filter givings eternal loading on top of existing loaded report
## What went wrong? 😲
Could possibly be from #4991 change. 

https://github.com/user-attachments/assets/04040454-634b-4ca8-8b4e-ed4bda0abf41

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to a report
2. Click on the filter button
3. cancel
4. See loading

## Your environment 🌱

- Open mSupply Version: 2.3-RC8
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by fergie-nz**
Fixes #5090

# 👩🏻‍💻 What does this PR do?

Adds check so set to loading isn't called if report arguments do not change

## 💌 Any notes for the reviewer?

# 🧪 Testing

Attempt to replicate issue in #5090 

# 📃 Documentation

- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour

### CODE REVIEW

**Review by andreievg — CHANGES_REQUESTED** [review]
@fergie-nz we actually already have isLoading state and that's fileId === undefined, but that also has to be combined with errorMessage state to show the right thing, I suggest we add a state object rather then keeping state with 3 different state variable: https://github.com/msupply-foundation/open-msupply/compare/5090-bug-fix-eternal-loading-...5090-bug-fix-eternal-loading-(Example-of-state-handling)

**Comment by andreievg** [comment]
There is also the excel export, which I think would take awhile, do you mind creating an issue for that ?

**Comment by fergie-nz** [comment]
> @fergie-nz we actually already have isLoading state and that's fileId === undefined, but that also has to be combined with errorMessage state to show the right thing, I suggest we add a state object rather then keeping state with 3 different state variable: [5090-bug-fix-eternal-loading-...5090-bug-fix-eternal-loading-(Example-of-state-handling)](https://github.com/msupply-foundation/open-msupply/compare/5090-bug-fix-eternal-loading-...5090-bug-fix-eternal-loading-(Example-of-state-handling))

That is awesome, thanks Andrei!

For some reason I had in my head that the iframe would take some time to render the report after making the request with the fileId, but I can see that is not the case on testing

**Review by andreievg — APPROVED** [review]
Looks great thanks Ferg !

**Pull request merged**
