### PR TITLE
3954 Link to documentation broken

### LINKED ISSUE #3954: Link to documentation broken
## What went wrong? 😲
Documentation links are broken

## Expected behaviour 🤔
Should lead to the correct documentation pages

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #3954

# 👩🏻‍💻 What does this PR do?
Adds doc links

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Go to `dashboard`, `assets`, `monitoring`, `sensors` and `equipment` and make sure they all lead to the right doc pages

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

**Review by clemens-msupply — APPROVED** [review]
Works fine, thank you! Docs look great by the way.

Nit, I wouldn't have expected that the docs link in the sidebar changes depending on where you are. I would have expected a docs link on the page or maybe in the footer?

**Comment by roxy-dao** [comment]
> Works fine, thank you! Docs look great by the way.
> 
> Nit, I wouldn't have expected that the docs link in the sidebar changes depending on where you are. I would have expected a docs link on the page or maybe in the footer?

The other doc links also link to the page that is relevant.. I'm sorry, I don't quite understand what you mean?

**Comment by roxy-dao** [comment]
> > > Works fine, thank you! Docs look great by the way.
> > > Nit, I wouldn't have expected that the docs link in the sidebar changes depending on where you are. I would have expected a docs link on the page or maybe in the footer?
> > 
> > 
> > The other doc links also link to the page that is relevant.. I'm sorry, I don't quite understand what you mean?
> 
> Yes just something that I wouldn't have expected as a user...

This is also explained in the docs :D

**Comment by roxy-dao** [comment]
> > > Works fine, thank you! Docs look great by the way.
> > > Nit, I wouldn't have expected that the docs link in the sidebar changes depending on where you are. I would have expected a docs link on the page or maybe in the footer?
> > 
> > 
> > The other doc links also link to the page that is relevant.. I'm sorry, I don't quite understand what you mean?
> 
> Yes just something that I wouldn't have expected as a user...

Do you mean because the other components in the AppDrawer doesn't do the same thing as the `Docs`? I guess the different behaviour is unexpected for the user... but this behaviour is explained in the docs (:

**Pull request merged**
