### PR TITLE
#4126 Fix stockline invalidation after repack

### LINKED ISSUE #4126: Pack Qty is not invalidated/updated after repack
## What went wrong? 😲

Pack Qty is not being invalidated after repack, so old quantity still shows on view stock detail page until refresh:

https://github.com/msupply-foundation/open-msupply/assets/55115239/f0faca28-bd3a-4806-86e6-251a00a4cf70

## Expected behaviour 🤔

Pack qty updates correctly after repack

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to stock line detail view
2. Note pack quantity
3. Repack some of that batch
4. Close repack modal
5. BUG: form still shows old pack quantity
6. Refresh page - now pack qty is accurate

## Your environment 🌱

- Open mSupply Version: 2.1
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #4126

# 👩🏻‍💻 What does this PR do?

Just removed `storeId` from the Repack query key -- not sure why we (I?) put this in the first place.

# 🧪 Testing

Make a repack from a Stock page. After closing the modal, the "Pack Qty" field should show the new (reduced) value.

### CODE REVIEW

**Review by roxy-dao — CHANGES_REQUESTED** [review]
Thanks Carl! Works great~

There was another extra request in the issue for when all of a stock line has been repacked. The message currently says: "Saved. The previous window has been closed since everything in this stock line has been repacked."

Can this be changed to: All stock has been repacked and this stock line will no longer show in the list. Click OK to be taken to the new stock line.

and user redirected to new stock line?

**Comment by CarlosNZ** [comment]
> There was another extra request in the issue for when all of a stock line has been repacked. The message currently says: "Saved. The previous window has been closed since everything in this stock line has been repacked."

Oops, I should really read the comments -- will do :)

**Comment by CarlosNZ** [comment]
@roxy, I've fixed the remaining invalidation, but I'm having a little trouble figuring out how to get the id of the newly created stockline at the same time as the decision whether to close the modal, so that's going to take a bit longer than I thought. Up to you if you want to merge this as-is or wait till next week. (I'm heading off now)

**Comment by roxy-dao** [comment]
> @roxy-dao , I've fixed the remaining invalidation, but I'm having a little trouble figuring out how to get the id of the newly created stockline at the same time as the decision whether to close the modal, so that's going to take a bit longer than I thought. Up to you if you want to merge this as-is or wait till next week. (I'm heading off now)

That's okay. No rush to get this into RC2

**Comment by CarlosNZ** [comment]
> That's okay. No rush to get this into RC2. Maybe you can get it from `to > invoice_row`?

Done now, @roxy-dao :)

**Review by roxy-dao — APPROVED** [review]
Brilliant~ Thanks <3

**Pull request merged**
