### PR TITLE
4590 Disable export button on Android

### LINKED ISSUE #4590: Disable export button on Android
haha or is it a feature request 🤷‍♀️ 

## What went wrong? 😲

On android, export button on basic reports does nothing.

https://github.com/user-attachments/assets/1fb94468-1ebf-44d8-bb4f-6850230316c0

I think this is consistent with the rest of the app, not being able to export on mobile, but elsewhere we have disabled the export button, which communicates the "you can't do this" a bit better

## Expected behaviour 🤔

Disabled export button on mobile

Unless you _should_ be able to export to excel, in which case, its not working 😁 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. On android
2. Create a report
3. Click export
4. Nada

## Your environment 🌱

- Open mSupply Version: V2.2.0 RC3
- Legacy mSupply Central Server Version:

- Platform: Android

- Database type: sqlite

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #4590

# 👩🏻‍💻 What does this PR do?

Disable export on android

# 🧪 Testing

- [ ] MUST BE ON ANDROID
- [ ] Set up reports
- [ ] Go to a report detail view
- [ ] The export button should be disabled.

# 📃 Documentation

- [x] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

**Comment by mark-prins** [comment]
is there a reason that we cannot export on android? 
when I check - the file is generated ok, and I can download the excel in android studio. Can we add a file save dialog to the android version? there should be a capacitor plugin for that

**Review by andreievg — APPROVED** [review]
Looks great thanks

**Comment by andreievg** [comment]
Oops i missed Mark's comment, but didn't we have issues with files ?
https://github.com/msupply-foundation/open-msupply/issues/3940

**Comment by andreievg** [comment]
> Can we add a file save dialog to the android version? there should be a capacitor plugin for that

I think the question should be added to carry over, thanks! As far as i am concerned ok to merge from now

**Pull request merged**
