### PR TITLE
4464 Report filter doesn't filter if you type too fast

### LINKED ISSUE #4464: Report filter doesn't filter if you type too fast
## What went wrong? 😲
The report filter doesn't correctly apply the text that was inputted if the user types/presses ok too fast

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Set up new reports in mSupply (download from reports repo)
2. Sync
3. Click on one of the reports
4. Type an item name really quickly and press Ok
5. See bug

## Your environment 🌱

- Open mSupply Version: 2.2
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #4464

# 👩🏻‍💻 What does this PR do?
Debounce ok button for args...  Still a bit finicky depending on how fast you type then click.... but I just type/click super fast... so maybe just me... 

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Set up new reports (run upsert command in folder, or download and upload to OG with StockAndItems or Expiring for context)
- [ ] Sync
- [ ] Go to report page
- [ ] Click on the report
- [ ] Enter in something for item name or code
- [ ] Press Ok

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

**Review by CarlosNZ — CHANGES_REQUESTED** [review]
This doesn't seem to work -- I can still type quickly in the input and click okay and the args aren't captured. 

I thought we were just going to disable the button while debouncing?

**Review by andreievg — DISMISSED** [review]
Looks great, thanks !

**Comment by roxy-dao** [comment]
> This doesn't seem to work -- I can still type quickly in the input and click okay and the args aren't captured.
> 
> I thought we were just going to disable the button while debouncing?

Can't disable the okay button, since the store preferences is being populated in data now... 👀

**Review by CarlosNZ — COMMENTED** [review]
Hey, just noticed that there is a (fortunately debounced) infinite re-render going on here too. (The `setData` method in `JsonForm` is being called every 750ms when the form is active even when nothing changes).

I don't think there's any rush to get this in though -- the original problem isn't a deal breaker, so we can keep experimenting.

**Comment by CarlosNZ** [comment]
> Hey, just noticed that there is a (fortunately debounced) infinite re-render going on here too. (The `setData` method in `JsonForm` is being called every 750ms when the form is active even when nothing changes).

Actually, this problem is already in the base branch. I might have a quick go at fixing this today.

**Comment by CarlosNZ** [comment]
> Actually, this problem is already in the base branch. I might have a quick go at fixing this today.

Okay, did a hotfix PR for the infinite re-render, as that needs to go into `develop` ASAP, whereas this is less urgent: https://github.com/msupply-foundation/open-msupply/pull/4483

**Pull request closed without merging**
