### PR TITLE
2882.2 update be crates

### PR DESCRIPTION
**Pull request by roxy-dao**
Part 2 of #2882

# 👩🏻‍💻 What does this PR do?
async_graphql changes... next up rustls changes, should be last PR

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Make sure tests still run and everything is working as should

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

**Comment by jmbrunskill** [comment]
@roxy-dao  how do you feel about pushing this out to 2.2?
After recent issues with crate updates I'm a little bit cauious for this release.
I've taken a quick look, but would like to understand why `async::trait` is not longer required for example.
If we're removing async::trait from all our loaders do we still need async trait at all, can it be removed as a dep?

**Comment by roxy-dao** [comment]
> @roxy-dao how do you feel about pushing this out to 2.2? After recent issues with crate updates I'm a little bit cauious for this release. I've taken a quick look, but would like to understand why `async::trait` is not longer required for example. If we're removing async::trait from all our loaders do we still need async trait at all, can it be removed as a dep?

https://github.com/async-graphql/async-graphql/pull/1468

**Review by jmbrunskill — APPROVED** [review]
Looks good Roxy, lets get this in develop.

**Review by jmbrunskill — APPROVED** [review]
Looks good Roxy! Thanks for the efforts on this!

**Pull request merged**
