### PR TITLE
3035 populate class category and type reference data as a migration

### LINKED ISSUE #3035: Populate class, category, and type reference data as a migration
## Is your feature request related to a problem? Please describe 👀

For cold chain equipment, we want to have some reference data pre-populated.

## Describe the solution you'd like 🎁
I've taken the PQS catalogue and put into a [spreadsheet](https://docs.google.com/spreadsheets/d/1X3K2dEd6kBT0aG76KmhDYcGOvQMENb-oetbeZzHUGko/edit?usp=drive_link) though there is a more [complete spreadsheet](https://docs.google.com/spreadsheets/d/1jYgxg2xn6meHH77IztgRcyuUaSo7BecQ/edit#gid=1770418819) with additional lookup information

### Moneyworks Jobcode 🧰
OMSCC:AST

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #3035 

# 👩🏻‍💻 What does this PR do? 
Adds the items from the WHO PQS catalogue via a migration

# 🧪 How has/should this change been tested? 
Works in sqlite and postgres

## 📃 Documentation

_No user facing changes_

### CODE REVIEW

**Review by mark-prins — COMMENTED** [review]
it's a bad dataset isn't it?
there's 
`'Vaccine/Waterpacks Freezer`
and
`Vaccine/Waterpack Freezer`

and inconsistent case with both

`Combined Refrigerator and Waterpack Freezer`
and
`Combined Refrigerator and waterpack freezer`

`Solar Direct Drive Refrigerator`
`Solar direct drive refrigerator TCW3043SDD`

etc.

**Comment by mark-prins** [comment]
`Vaccine Carrier Freeze-Free`
`Freeze Free Vaccine carrier`

`Freeze Free Vaccine Carrier Short Range`
`Freeze-free Vaccine carrier, Long range`

where is the consistency!!

two entries for `Vaccine Carrier Long range`?

**Comment by adamdewey** [comment]
Ooh, nasty - but good spot! 

Where is the master spreadsheet? 

If you like I can go through and clean up the data @mark-prins ?

**Comment by jmbrunskill** [comment]
> Ooh, nasty - but good spot!
> 
> Where is the master spreadsheet?
> 
> If you like I can go through and clean up the data @mark-prins ?

That would be great @adamdewey 

Here's the spreadsheet I used...
https://docs.google.com/spreadsheets/d/1X3K2dEd6kBT0aG76KmhDYcGOvQMENb-oetbeZzHUGko/edit?usp=drive_link

`Original`

https://docs.google.com/spreadsheets/d/1jYgxg2xn6meHH77IztgRcyuUaSo7BecQ/edit#gid=1770418819

**Review by mark-prins — CHANGES_REQUESTED** [review]
I was thinking to import from a csv or spreadsheet as I thought that would make it fairly easy to update the data. happy with the sql insert though, that's nice and easy to read.

There's an issue importing to postgres - to fix this I've had to massage the data which I've put in [this branch](https://github.com/msupply-foundation/open-msupply/compare/3035-populate-class-category-and-type-reference-data-as-a-migration1...3035-populate-class-category-and-type-reference-data-as-a-migration1(data-tidy))

can you have a quick look? The unique constraint in postgres didn't allow duplicates, so I've had to remove and remap those, and while doing that I fixed up the typo and inconsistent capitalisation.

**Comment by mark-prins** [comment]
Oh sorry @adamdewey! you were too quick. I was already fixing the data..

I haven't updated the source spreadsheets though, I've made the change in a new branch. maybe just leave it for now?
the data still isn't great, but it's better and the exact duplicates are gone. I've also changed things like `Freeze-Free Vaccine carrier short-range` into `Freeze-Free Vaccine Carrier Short Range` since that format was more popular.

**Comment by jmbrunskill** [comment]
> I was thinking to import from a csv or spreadsheet as I thought that would make it fairly easy to update the data. happy with the sql insert though, that's nice and easy to read.
> 
> There's an issue importing to postgres - to fix this I've had to massage the data which I've put in [this branch](https://github.com/msupply-foundation/open-msupply/compare/3035-populate-class-category-and-type-reference-data-as-a-migration1...3035-populate-class-category-and-type-reference-data-as-a-migration1(data-tidy))
> 
> can you have a quick look? The unique constraint in postgres didn't allow duplicates, so I've had to remove and remap those, and while doing that I fixed up the typo and inconsistent capitalisation.

I wrote a quick python script to translate the csv to inserts, the problem is that if I re-run it I get all new IDs now. Probably doesn't hurt to have a csv would be easier to update, we'd need to embed it in the rust code though. If we want to update via and API, and or update a csv, it might be better to do it a different way. Hopefully this is a good quick start option at least...

**Comment by adamdewey** [comment]
Oh thanks @mark-prins - yeah, am just having a look through the spreadsheet now. 

Definitely some improvements we could make - taking out volume from the type etc

Was also wanting to consult with @anisha-msupply about whether we would be best to go with `Title` ('Freeze-Free Vaccine Carrier Short-Range') or `Sentence` ('Freeze-free vaccine carrier short-range') case for capitalisation. 

`Sentence` case is easier to read, `Title` is more formal.

Perhaps some mock-ups could help us to decide which is more suitable?

**Comment by mark-prins** [comment]
> Perhaps some mock-ups could help us to decide which is more suitable?

fwiw I like the sentence case, but the Title Version was More Often Used.. so I went that way.

We should have a working version up soon, so there's no need to ask for a mock up. Probably quicker to do a search and replace to update the script and take a screenshot of the site. would appreciate some opinions though, thanks!

**Comment by adamdewey** [comment]
Thanks @mark-prins . 

Here's a sanitised version: https://docs.google.com/spreadsheets/d/1X3K2dEd6kBT0aG76KmhDYcGOvQMENb-oetbeZzHUGko/edit#gid=147252663

I feel like there could be some improvement in terms of separating the function (e.g. refrigerator, freezer) from the method (e.g. solar direct drive, mains, ice-lined etc) but it's at least a bit cleaner than before!

**Comment by jmbrunskill** [comment]
@mark-prins I've updated to Adam's sanitised version. Look ok for you?
I haven't done any sort of csv import at this stage. There's a few complications there that I don't think are high priority to resolve at this stage.

**Review by mark-prins — APPROVED** [review]
👍  much neater, thanks @adamdewey & @jmbrunskill!
imports fine on postgres, so there's no dupes.

**Pull request merged**
