### PR TITLE
2429 change formatter.naive date time to formatter.to iso string

### LINKED ISSUE #2429: Change Formatter.naiveDateTime  to Formatter.toISOString
From comment: https://github.com/openmsupply/open-msupply/pull/2412#discussion_r1380874419

From the only use-case we have, we need `toISOString()`, i.e. we need it in an API call. (naiveDateTime would suggest no timezone to me)

- [ ] rename existing method to `toISOString` and use the correct `Date.toISOString()` format

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #2429 

# 👩🏻‍💻 What does this PR do? 
Return iso string to api for datetime and fix tests

# 🧪 How has/should this change been tested? 
- [ ] try use any of the datetime filters and check api call to see the parameters sent

### CODE REVIEW

**Review by mark-prins — APPROVED** [review]
👍  thanks!

**Comment by roxy-dao** [comment]
Oh opps... I thought this was branched off 1.5.0...

**Comment by mark-prins** [comment]
do you mean 'this should have been in 1.5.0'? if so- I think ok to leave until develop gets merged into 1.6.0, this change isn't critical

**Comment by roxy-dao** [comment]
> do you mean 'this should have been in 1.5.0'? if so- I think ok to leave until develop gets merged into 1.6.0, this change isn't critical

Yup! Since it's a cold chain filter bug >.<

**Comment by mark-prins** [comment]
ah. yes, have tested.. I withdraw my previous comment.

**Pull request merged**
