### PR TITLE
1404 Add some logging to migrations

### LINKED ISSUE #1404: Add some logging to migrations
## Is your feature request related to a problem? Please describe 👀
Coming from #1392 - the issue there is in the diesel migrations.
However the `migrations/mod.rs` file has this:

```
// TODO logging
pub fn migrate(
```

I'd like to have some logging.

## Describe the solution you'd like 🎁
I'm unsure of the intention of the TODO comment. At the least I'd like the error thrown by the diesel migration to be logged ( I was unable to see it in the log I checked ) and if the migration drops out due to version mismatch etc, then that should be logged, at an error level. 

Please check that the current _panic_ will get logged - if so, then that's sufficient.

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #1404

# 👩🏻‍💻 What does this PR do?
Logs migration errors

# 🧪 Testing

- [ ] Change json version to lower than database version
- [ ] Have logging set to 'Error'
- [ ] Run
- [ ] Check log, error should have been logged

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

**Review by CarlosNZ — COMMENTED** [review]
Seems good, although we're already seeing the error when it panics and stops.

Before:
Screenshot 2024-08-23 at 12 24 38 PM

After:
Screenshot 2024-08-23 at 12 23 15 PM

Do we need both?

**Comment by CarlosNZ** [comment]
@andreievg had a suggestion to capture the panic error and log it as an Error.

**Comment by roxy-dao** [comment]
> Seems good, although we're already seeing the error when it panics and stops.
> 
> Before: Screenshot 2024-08-23 at 12 24 38 PM
> 
> After: Screenshot 2024-08-23 at 12 23 15 PM
> 
> Do we need both?

The log file doesn't have the log... only in console...

**Comment by andreievg** [comment]
We would just need to enable [this](https://github.com/msupply-foundation/open-msupply/blob/3615e4b961f3cf65221baca099266f58a9a7ca2d/server/android/src/android.rs#L69) in `server/src/main.rs` (not in `server/src/lib.rs`, as lib.rs is used by windows service which already does something else with [panic](https://github.com/msupply-foundation/open-msupply/blob/3615e4b961f3cf65221baca099266f58a9a7ca2d/server/windows/src/windows.rs#L70-L71))

Btw i am making conclusion that https://github.com/msupply-foundation/open-msupply/issues/1404 is only for mac or linux build/dev work. And related issue https://github.com/msupply-foundation/open-msupply/issues/1392, has already been fixed with panic logging in android 

I've committed my change straight to this branch since Roxy is away, please re-review and merge if happy thanks, thanks.

**Review by CarlosNZ — APPROVED** [review]
LGTM, will merge :)

**Pull request merged**
