### PR TITLE
4657 vaccine course dose soft delete

### LINKED ISSUE #4657: Persist/soft delete vaccine course doses
Currently, every time a vaccine course is edited, each vaccine_course_dose is deleted and recreated.

However, we need to implement soft deletes for vaccine_course_dose, which means the delete all and recreate will no longer suit. Instead, we should receive the current list of vaccine_course_dose from the frontend, and compare that with all the vaccine_course_dose that we have for that vaccine_course.

Any that aren't in the current list should be soft deleted - all others can be upserted. 

It should be noted (in the code) that we are soft-deleting so as not to break references for patients that have already received that dose.

- [ ] Implement soft delete of vaccine_course_dose (for when a user explicitly deletes a dose)
- [ ] Upsert remaining vaccine_course_doses provided by the frontend

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #4657 

# 👩🏻‍💻 What does this PR do?

Soft deletes vaccine course doses, so you can edit a vaccine course now 🎉 

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Run unit tests
- [ ] Create some vaccinations for a patient for a specific dose/course
- [ ] Now edit that course
- [ ] Even delete the dose
- [ ] You can save the vaccine course fine
- [ ] Vaccination records are still there :)

# 📃 Documentation

- [x] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

**Comment by CarlosNZ** [comment]
First thing I noticed: the deleted course doses don't appear in the Vaccination Modal any more, even though they still appear in the card list:
Screenshot 2024-09-25 at 2 08 18 PM

Also, wondering -- obviously we want to display the previously existing items in the Vax card list once the vaccination record exists. But for doses they haven't had yet, should we still display them? Are patients supposed to be able receive doses that have been removed from the course?

**Review by CarlosNZ — CHANGES_REQUESTED** [review]
Looks good as far as the delete logic goes. Just need to make sure the vaccination card can still display the details for the deleted doses.

**Comment by lache-melvin** [comment]
Ah great point! Yeah I think existing ones should continue to be visible, but shouldn't be able to create new vaccinations. There might be an edge case where they delete a dose, let's say "dose 2", and create a new dose also called "dose 2"... the cards would have 2 lines in them both called "dose 2", one given and one blank... not much we can do in that case though, and I think pretty low probability

**Comment by lache-melvin** [comment]
Thanks for catching Carl!

- Only show deleted dose on card if there is an existing vaccination: [69b36a7](https://github.com/msupply-foundation/open-msupply/pull/4868/commits/69b36a79bcb8ba6d711f261c155e265fedbd690a)
- Display modal correctly: [3fb9567](https://github.com/msupply-foundation/open-msupply/pull/4868/commits/3fb95673c9ea28c831f325fa37ffd5e6b3c34f01)

**Review by CarlosNZ — APPROVED** [review]
Great, thanks for the fixes :)

**Pull request merged**
