### PR TITLE
5645 abbreviations table

### LINKED ISSUE #5645: Create & sync Abbreviations Table
In mSupply see `Special -> Abbreviations...`
image

Tasks
- [x] New Database table in oms `abbreviation`
- [x] AbbreviationRepositoryRow (find_by_id, delete)
- [x] Translations for `Upsert` and `Delete`

### PR DESCRIPTION
**Pull request by Chris-Petty**
Fixes #5645 

# 👩🏻‍💻 What does this PR do?

Adds migration, repo and sync logic for the `abbreviation` table

### CODE REVIEW

**Comment by Chris-Petty** [comment]
Hmm we should probably have a migration after creating the table that attempts to reintegrate the sync buffer to populate the table.

**Comment by jmbrunskill** [comment]
> Hmm we should probably have a migration after creating the table that attempts to reintegrate the sync buffer to populate the table.


I agree something like this should do it.

```
        // Reset translate all items on the next sync
        sql!(
            connection,
            r#"
            UPDATE sync_buffer SET integration_datetime = NULL WHERE table_name = 'abbreviation';
        "#,
        )?;
```

**Comment by jmbrunskill** [comment]
> > Hmm we should probably have a migration after creating the table that attempts to reintegrate the sync buffer to populate the table.
> 
> I agree something like this should do it.
> 
> ```
>         // Retranslate/integrate all abbreviations on the next sync
>         sql!(
>             connection,
>             r#"
>             UPDATE sync_buffer SET integration_datetime = NULL WHERE table_name = 'abbreviation';
>         "#,
>         )?;
> ```

Hmmm actually doesn't seem to be needed, everything got translated for me...

**Review by jmbrunskill — APPROVED** [review]
Nice! Works for me, thanks Chris

**Comment by Chris-Petty** [comment]
> Nice! Works for me, thanks Chris

Oh haha, I ended up committing it. I will revert. In hindsight not being a supported table it probably got ignored up till now anyway?

**Pull request merged**
