### PR TITLE
Easter egg

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #Nothing

# 👩🏻‍💻 What does this PR do? 
 
The PR that no one asked for 😉 
Thought it might be fun to add an easter egg.. so had a play with the idea.
Press `e` `e` to get this:

https://github.com/msupply-foundation/open-msupply/assets/9192912/8a7f6bf2-efc5-4b69-aedf-0dd6f12ef392

you then have to click on the mSupply guy.. then space or arrow up to start. Arrow up or down key to play.

### CODE REVIEW

**Comment by GaryWilletts** [comment]
@mark-prins I love it, but surely he should be trying to deliver the meds in his hand, so he needs to jump to hit something and duck to get something else - he misses a delivery and the game is over.

I can see the in-country WhatsApp support groups filling with photos of facility high scores. There will be mSupply guy leagues and ladders... You have unleashed a phenomenon...

**Comment by roxy-dao** [comment]
Omg <3 you implemented it (: Best easter egg ever!

**Comment by GaryWilletts** [comment]
@mark-prins I think we need to unleash an Easter egg hunt...Time for a blog entry when it's released?

**Review by roxy-dao — APPROVED** [review]
I love it <3

**Pull request merged**
