### PR TITLE
Remove mock service workers, update node version

### LINKED ISSUE #4154: Remove mock service workers
## The suggestion

Remove mock service workers from frontend

### Why should we invest time in this?

Less compilation required (generated operations files get mock service worker lines created.
e.g.
```
/**
 * @param resolver a function that accepts a captured request and may return a mocked response.
 * @see https://mswjs.io/docs/basics/response-resolver
 * @example
 * mockTemperatureLogsQuery((req, res, ctx) => {
 *   const { page, sort, filter, storeId } = req.variables;
 *   return res(
 *     ctx.data({ temperatureLogs })
 *   )
 * })
 */
export const mockTemperatureLogsQuery = (resolver: ResponseResolver<GraphQLRequest<Temperature_LogsQueryVariables>, GraphQLContext<Temperature_LogsQuery>, any>) =>
  graphql.query<Temperature_LogsQuery, Temperature_LogsQueryVariables>(
    'temperature_logs',
    resolver
  )
```

Less dependancies included in yarn lock.

Less risk of msw type being accidentally imported during development work.

### Are there any risks associated with this change?

Low risk it's not being used anywhere,and only used for development tasks anyway.

### How much effort is required?

"This change is trivial, it will take less than 1 hour to implement."

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #4154 

# 👩🏻‍💻 What does this PR do?

Removes mock service workers from the main code base.
I've kept it as a dev dependancy as there's one test that needs it. (useNextItem.test.tsx)

If that test's not needed, it could be removed completely.

## 💌 Any notes for the reviewer?

- [ ] There's something to do with story book that I removed, so I might have broken that?
- [ ] Had weird issues with `yarn generate` seems like maybe it's less stable with so many changes, had to manually fix some files.

# 🧪 Testing

- [ ] General check that things are still working?

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

**Comment by mark-prins** [comment]
`yarn install` and then `yarn start-local` gives me this:

Screenshot 2024-07-03 at 11 16 18 AM

🤔

**Comment by jmbrunskill** [comment]
Hmmm, maybe I didn't actually test it, just ran yarn compile...
Will take a look after lunch.

**Comment by mark-prins** [comment]
all good it's running for me. just looking at removing the test too.
there's a couple things I had to change:

* webpack.config.js remove the `mockServiceWorker.js` in `CopyPlugin`
* in `.storybook/preview.js` there's a reference to `msw-storybook-addon` which has been removed

**Review by mark-prins — APPROVED** [review]
🙏  thanks James - all good.

have made a few changes, which I've committed. you might want to eyeball..

have run the site, run `generate`, jest test suite and storybook.. all good.

**Comment by jmbrunskill** [comment]
Thanks Mark, looks good! Nice to get rid of it completely, rather than relying on it in tests.

**Pull request merged**
