### PR TITLE
#4224 Drop and recreate Views

### LINKED ISSUE #4424: Sync R&R forms to OMS central server
## Is your feature request related to a problem? Please describe 👀

R&R forms need to be synced, in order to be backed up.

## Describe the solution you'd like 🎁

These should be synced to the OMS central server.

### Moneyworks Jobcode 🧰

[DFAT:TDEV]

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #4424

# 👩🏻‍💻 What does this PR do?

Adds functionality to drop all views before migration runs, then re-create them afterwards.

This means that, from now on, any changes to views can be done directly on the view rather than having to add additional migration to change them.

## 💌 Any notes for the reviewer?

I've handled the error, in that the server will panic and stop if there is an error in the SQL mutations. However, I'd like to be able to bring through the actual error message from the database and print that out -- is that possible @andreievg ?

What did you want to do for test functions, @andreievg ?

# 🧪 Testing

- [ ] Check all views are correct after starting server
- [ ] Manually delete all the views. Re-start the server and they should all be re-instated.
- [ ] Check for postgres as well as SQLite
- [ ] Set the database version to something below 2.2.0 and the drop/rebuild shoudn't run (won't print anything to console)

### CODE REVIEW

**Comment by andreievg** [comment]
>  However, I'd like to be able to bring through the actual error message from the database and print that out -- is that possible 

Yep, just have to store the error in the enum variant, as per below suggestion

> What did you want to do for test functions, @andreievg ?

I was hoping that test functions already exist on all of the view, i pretty confident they exist on most (and the rest should be used in reports, which we would add tests for anyways).

I actually couldn't see the migration run when migrating from scratch (i.e. when wiping database and doing `cargo run`). Code suggest they should run during startup if we are already on certain database version, but not as we migrate to that version or past that version from earlier version. I had a play around and this should work

https://github.com/msupply-foundation/open-msupply/compare/4224-drop-and-recreate-views...4224-drop-and-recreate-views(Drop-and-re-create-view-when-database-is-migrating)

There is an issue with postgres views and postgres migration (actually first of all there is a fix in develop for PgType on NameTypeRow, that might need to be pulled in). I'll make a separate issue about it shortly. Postgres tests actually fail

**Comment by andreievg** [comment]
By the way for view that are different between postgres and sqlite, it's probably best to show the difference -> conditionally change just part of the view that is different (this can be done in another issue)

**Comment by andreievg** [comment]
@CarlosNZ i did another check and I think the invoice_stats needs to be swapped (sqlite and postgres):
https://github.com/msupply-foundation/open-msupply/compare/4224-drop-and-recreate-views...4224-drop-and-recreate-views(Swap-postgres-and-sqlite-invoice-line-view)

**Comment by andreievg** [comment]
@roxy-dao i merged my suggested change, then added the latest changes to the requisitions_in_period view (from one of the RC), re-run tests for postgres and sqlite and also added something about adding to internal docs in this issue: https://github.com/msupply-foundation/open-msupply/issues/4579

It should be ready to merge i think

**Review by roxy-dao — APPROVED** [review]
LGTM ~ Thanks Andrei and Carl (:

**Comment by roxy-dao** [comment]
Merged into wrong branch, but have merged develop into 2.2 since no new PRs have gone into develop >.>

**Pull request merged**
