### PR TITLE
Update GAPS Enums for Gas and Kerosene

### LINKED ISSUE #4165: GAPS: Update enums for Gas, Kerosene, Solar and Electricity
## What went wrong? 😲

Gas and Kerosene Availability doesn't make sense

## Expected behaviour 🤔

The enums should be: 

- No availability
- Available
- Irregular
- Unknown

Solar and Electricity should also have an `Unknown` option added

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Click Edit next to your logged in store
2. Check options under Gas and Kerosene availability

## Your environment 🌱

- Open mSupply Version:Develop

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #4165 

# 👩🏻‍💻 What does this PR do?

Adds new options for gas and kerosene

image

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] You'll need to configure gaps properties from Central Server -> Settings -> GAPS
- [ ] Edit your store, check the correct options are showing under Gas and Kerosene availablity

# 📃 Documentation

- [X] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

**Review by lache-melvin — APPROVED** [review]
🙏

**Comment by lache-melvin** [comment]
Oh, per issue:

> Solar and Electricity should also have an Unknown option added

**Comment by lache-melvin** [comment]
Haha, also while here, noticed that [this issue](https://github.com/msupply-foundation/open-msupply/issues/4160) also mentioned including `safety buffer stock`?

**Comment by jmbrunskill** [comment]
> Haha, also while here, noticed that [this issue](https://github.com/msupply-foundation/open-msupply/issues/4160) also mentioned including `safety buffer stock`?

This one is a bit more uncertain. We already have something similar in mSupply.
image

@mark-prins can you confirm if we should add this as a name property?

**Comment by adamdewey** [comment]
> This one is a bit more uncertain. We already have something similar in mSupply.

The remote users won't be able to access OG though - so we at least need to provide them a way to set it via OMS and link it to that value in OG

**Pull request merged**
