### PR TITLE
2502 restrict pack variant editing to central server

### LINKED ISSUE #2502: Restrict pack variant editing to omSupply central server
Restrict editing of pack variants for omSupply central server only (would still be visible though), this is to be done in service and graphql permissions. Carry over from #2309 

### Moneyworks Jobcode 🧰
OMS:NEST

### PR DESCRIPTION
**Pull request by andreievg**
Fixes #2502 

# 👩🏻‍💻 What does this PR do? 

* add isCentralServer graphql query (no permission check, should it have ?)
* move central server graphql mutations behind centralServer endpoint (idea is to have one place where isCentralServer is checked)
* add isCentralServer api query to front end, and useIsCentralServerOrWarning hook to help with central server checks
* disallow deleting of pack variant when user doesn't have permission (this was done for editing and for creating pack variants but not for delete)
* Silently ignore sync error to omSupply central server, this is just temporary, this point is in carry over issue, we can discuss this tomorrow as it's in the [carry over issue](https://github.com/msupply-foundation/open-msupply/issues/2821)

# 🧪 How has/should this change been tested? 

Start server in central server mode:
IS_CENTRAL_SERVER=true cargo run
make sure user has this permission (if not tick enable it and re-login):
Screenshot 2024-01-31 at 5 01 16 PM
- [ ] go to item and pack_variant tab, try adding a pack variant (should be able to add)
Remove above permission from user (and re-login)
- [ ] go to item and pack_variant tab, try selecting pack variant deleting it (should get permission error).
Stop server and start in remote site mode
`cargo run`
- [ ]  go to item and pack_variant tab, try deleting, adding new pack variant or editing existing one, should get an error saying this operation is only allowed on central server

## 📃 Documentation

_No user facing changes_

or

- [ ] Functional change 1
- [ ] Functional change 2

### CODE REVIEW

**Comment by mark-prins** [comment]
I didn't see where you mentioned which mSupply branch to use. I've used develop and cannot find the permission

**Comment by mark-prins** [comment]
@andreievg There's a fundamental bug which has come from a different PR. 
In `Host.tsx` the `<Init />` will need to be moved to be under the `<AuthProvider>`. As it stands, the store id is always `store-id` and therefore the permission check fails. I can add a new variant, but then it doesn't show me the change because the store id is incorrect

**Comment by mark-prins** [comment]
Can you tweak the UI please?
The select drop down should be on the right, nearer the checkboxes. Perhaps it has to go under the 'new pack variant' button.

Also - the select doesn't make sense when there is no table, because it isn't clear that there is a table:

Screenshot 2024-02-07 at 12 17 59 PM

Can we hide it in this case?

**Comment by Chris-Petty** [comment]
Testing github actions

**Review by mark-prins — CHANGES_REQUESTED** [review]
Working as described - once I fixed the store ID problem I had. Couple of things to change, as noted.

Can you update the Host.tsx, and preferably, update the layout of the pack unit editing please?

Can you also update the comment in `Host.tsx` please? The text says 'api keys' but I think it should be 'cache keys':

```
// They will be refetched on page reload or when store is changed based on cache usePackUnits cache keys
```

and a typo in `usePackVariants`

```
// or if store is changed (based on api keys)
```

there's a 'd' missing from the end of changed 🙏

**Comment by andreievg** [comment]
@mark-prins thanks for review

In this commit: 8800bd36d2473a4d81322f539e966f86a44a59c1

* Fixed comments, api -> cache, Unit -> Variatns
* Relocated <Init> to be within AuthProvider
* Boolean -> boolean
* I moved drop down to the right in pack variant view (as per screenshot), first it was under the button, and it seemed to use too much vertical space, which is very limited on tablets, so just added drop down next to button (toggled via visibility rather then conditional rendering). I couldn't figure out easy way to see if there are rows in the table, i added isEmpty to useTableState, which was changes when setRows was called, but that didn't 'hide' dropDown when the last row was deleted ¯\_(ツ)_/¯, so I left it as TODO). How to check there are no rows ? Also the drop down is visible in other views, is there an issue to change that ? (see last screenshot)
* Renamed hook, although i settled for slightly longer but more explicit naming. Thanks for the suggestions and identifying as confusion, it really was confusing (might still be)

Also added 'd' to change -> ac1bebdb104746e54800380be0a226dcf6f667d1

> doOrDie which isn't helpful but I like it

Haha I wish we could have a bit more fun with variable names like this. But it's public repo hehe

**Review by mark-prins — APPROVED** [review]

**Comment by mark-prins** [comment]
cool - thanks for the changes @andreievg! looking good

**Comment by andreievg** [comment]
@mark-prins thanks for review !

**Pull request merged**
