### PR TITLE
4357 Set Quantities to 0 in Inbound Shipment doesn't work and shows incorrect error

### LINKED ISSUE #4357: Set Quantities to 0 in Inbound Shipment doesn't work and shows incorrect error
## What went wrong? 😲

When navigating to `Replenishment -> Inbound Shipment`, you can select a line in a new Inbound Shipment. Once an item is selected, you can then click `Actions -> Set Quantities to 0` and that's when 2 incorrect errors pop up. The item I was using had **quantity > 0** and the status of the Inbound Shipment was **New**. 

## Expected behaviour 🤔

If the requirements are satisfied (e.g. the Inbound Shipment is New and quantity > 0), then you should be able to perform the function and set quantities to 0.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to `Replenishment -> Inbound Shipment`
2. Create a new Inbound Shipment and add an item to it
3. Select that item, go to `Actions -> Set Quantity to 0`
4. See 2 errors pop up

## Your environment 🌱

- Open mSupply Version: V2.1.0-RC4
- Legacy mSupply Central Server Version: V7.15.05

- Platform: Desktop app on Windows and Galaxy Tab A8 Android App

- Database type: SQLite3

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #4357

# 👩🏻‍💻 What does this PR do?
Mostly side quests to get the frontend running again... since the NumberOfPacksBelowZero commits + store is disabled commits are gone... 

The actual fix has also been removed from GH mysteriously somehow so have added a note to not check <= 0

# 🧪 Testing

- [ ] Have a new inbound shipment with some lines with quantites
- [ ] Select the lines
- [ ] Click Action -> Set quantities to 0
- [ ] Should be able to 0 out lines

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

**Comment by andreievg** [comment]
@roxy-dao keen to approve but I am a bit confused about the following:

> Mostly side quests to get the frontend running again... since the NumberOfPacksBelowZero commits + store is disabled commits are gone...

The only diff is the `note`

Also I can't quite replicate the issue on develop

**Comment by roxy-dao** [comment]
> @roxy-dao keen to approve but I am a bit confused about the following:
> 
> > Mostly side quests to get the frontend running again... since the NumberOfPacksBelowZero commits + store is disabled commits are gone...
> 
> The only diff is the `note`
> 
> Also I can't quite replicate the issue on develop

It got fixed when that huge 'problematic' commit happened XD

**Comment by andreievg** [comment]
> It got fixed when that huge 'problematic' commit happened XD so have added note to make sure it doesn't get changed again

Ohh i see, best way for this is usually tests.

**Review by andreievg — APPROVED** [review]
Thanks @roxy-dao

**Comment by roxy-dao** [comment]
> > It got fixed when that huge 'problematic' commit happened XD so have added note to make sure it doesn't get changed again
> 
> Ohh i see, best way for this is usually tests.

There was a test... it got changed...

**Pull request merged**
