### PR TITLE
UI improvements for pack variant

### LINKED ISSUE #3107: Merge pack variant into development
* Update pack variants from development
* PR for full pack variants
* Check all UI areas, compare with develop (good time for writing external documentation, and test docs ?)

### PR DESCRIPTION
**Pull request by andreievg**
Fixes #3107

# 👩🏻‍💻 What does this PR do? 

Minor UI/UX improvements for pack variant.

### Stocktake Before

Screenshot 2024-02-29 at 9 50 09 PM

### Stoktake After

Screenshot 2024-02-29 at 9 49 37 PM

### Stocktake Line Edit Before

Screenshot 2024-02-29 at 9 52 39 PM

### Stocktake Line Edit After

Screenshot 2024-02-29 at 9 53 04 PM

Inbound shipment before and after pretty much the same as Stocktake

### Outbound Shipment Before

Screenshot 2024-02-29 at 9 56 03 PM

### Outbound Shipment After

Screenshot 2024-02-29 at 9 55 26 PM

### Internal Order Before

RequestReqBefore

Screenshot 2024-02-29 at 10 05 37 PM

### Internal Order After

RequestReqAfter

Screenshot 2024-02-29 at 10 03 51 PM

# 🧪 How has/should this change been tested? 

Use this reference data export
[reference2.zip](https://github.com/msupply-foundation/open-msupply/files/14445692/reference2.zip)

put it in server/data folder

run 

```
cargo run --bin remote_server_cli -- initialise-from-export -n reference2
cargo run --bin remote_server_cli -- refresh-dates
```

Above should give data with amc for `Amoxicillin 250mg tabs`

Run as central server with `IS_CENTRAL_SERVER=true cargo run`. Now should be able to configure pack variants for `Amoxicillin 250mg tabs` in item -> pack variant.  Can change between this branch and `UI-tweaks-for-pack-variant` and see the above changes

## 💌 Any notes for the reviewer?

I also changed unit/pack display for items that don't have pack/variant defined, they will show now as "Tablet" or "100 x Tablet", vs "1 Tablet' and "100 Tablet",  think  this single column is actually better to understand then having separate Unit and Pack columns.

There are still changed to be done to Outbound/Prescription line edits, but that will follow up in another PR. Also noticed that ResponseRequisition doesn't actually have Pack Variant controls, Will add issue/PR

### CODE REVIEW

**Comment by jmbrunskill** [comment]
@andreievg have you given thought to Central Server needing to have access to all items to add pack variants?
I had to add a master list with all items on it, before I can edit the pack variants in my OMS store...

**Comment by jmbrunskill** [comment]
image
Default stock take batch line seems to not allow setting pack variant, you have to add one first?
This might be deliberate but feels a bit broken when there's no batches for the item...

**Comment by jmbrunskill** [comment]
Stock take doesn't update when clicking ok?
These should all have counted packs...
image
Maybe related to this, but should already be in the branch right?
https://github.com/msupply-foundation/open-msupply/issues/3048

**Comment by jmbrunskill** [comment]
image

vs

image


In the drop accordian it says there two stock lines with `Tab` but one actually doesn't have a variant assigned and I can't seem to assign one too it...

**Comment by jmbrunskill** [comment]
In outbound shipment the `Pack` field seems to push the qty edit box off the screen?
image

**Review by jmbrunskill — APPROVED** [review]
Happy to approve this.
Raised a few issues that might be found in testing and or warrent new issues to be raised?

I see you're established a `PACK_VARIANT_ENTRY_CELL_MIN_WIDTH` which seems good but other fields are hardcoded like `unit` to 130? Is it worth applying that pattern further?

**Comment by andreievg** [comment]
@jmbrunskill, thanks a lot for review !

> Default stock take batch line seems to not allow setting pack variant, you have to add one first?
> This might be deliberate but feels a bit broken when there's no batches for the item...

In your screenshot it looks not editable, i can't seem to reproduce this, however it should default to active pack variant, which I've just updated in the latest commit, would be interested to see your data set for this.

> Stock take doesn't update when clicking ok?

It wasn't quite in the branch, since the merge started before this fix, double checked, seems to work.

> Actually I take it back, it seems like the first pack variant is sometimes assigned to the row even if an error occurs even though it was not selected before. Possibly only if there's just one pack variant?

Would be great if you can show me how to reproduce this one

> In outbound shipment the Pack field seems to push the qty edit box off the screen?

Great point, will fix it up before merging

**Comment by andreievg** [comment]
@jmbrunskill thanks for your review, i've updated as much as i can for now, really wanted to merge the pack variant feature, and it required changes in this PR. Will revisit when I am back

**Pull request merged**
